### ISSUE TITLE
As a product manager, I want to ship products and features using a design system, so that they appear consistent and on brand, and can be delivered with greater velocity.

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-com#392]

**Comment by adamsoffer** [comment]
## Requirements
- Should support light and dark mode
- The font family should remain `Inter`. 
- Should be implemented published as a standalone package inside the `livepeer-com` repo
- Should extend the [Radix UI design system](https://design-system.radix-ui.vercel.app/) (built with [Stitches](https://stitches.dev) and [Radix UI Primitives](https://radix-ui.com/primitives/docs/overview/introduction))


## Tasks
**Visual Styles**
- [ ] Color [Design]
- [ ] Color [Code]

**UI Components**
- [ ] Accordian [Design]
- [ ] Accordian [Code]
- [ ] Alert Dialog [Design]
- [ ] Alert Dialog [Code]
- [ ] Avatar [Design]
- [ ] Avatar [Code]
- [ ] Badge [Design]
- [ ] Badge [Code]
- [ ] Buttons [Design]
- [ ] Buttons [Code]
- [ ] Card [Design]
- [ ] Card [Code]
- [ ] Checkbox [Design]
- [ ] Checkbox [Code]
- [ ] Context Menu [Design]
- [ ] Context Menu [Code]
- [ ] Context Menu [Design]
- [ ] Context Menu [Code]
- [ ] Control Group [Design]
- [ ] Control Group [Code]
- [ ] Code [Design]
- [ ] Code [Code]
- [ ] Dialog [Design]
- [ ] Dialog [Code]
- [ ] Dialog [Design]
- [ ] Dialog [Code]
- [ ] Dropdown Menu [Design]
- [ ] Dropdown Menu [Code]
- [ ] Input [Design]
- [ ] Input [Code]
- [ ] Link [Design]
- [ ] Link [Code]
- [ ] Popover [Design]
- [ ] Popover [Code]
- [ ] Progress Bar [Design]
- [ ] Progress Bar [Code]
- [ ] Radio [Design]
- [ ] Radio [Code]
- [ ] Radio Card [Design]
- [ ] Radio Card [Code]
- [ ] Slider [Design]
- [ ] Slider [Code]
- [ ] Status [Design]
- [ ] Status [Code]
- [ ] Status [Design]
- [ ] Status [Code]
- [ ] Switch [Design]
- [ ] Switch [Code]
- [ ] Tab Link [Design]
- [ ] Tab Link [Code]
- [ ] Tab Link [Design]
- [ ] Tab Link [Code]
- [ ] Tabs [Design]
- [ ] Tabs [Code]
- [ ] Text [Design]
- [ ] Text [Code]
- [ ] Textarea [Design]
- [ ] Textarea [Code]
- [ ] Skeleton [Design]
- [ ] Skeleton [Code]
- [ ] Verified Badge [Design]
- [ ] Verified Badge [Code]
